# Generated by Django 4.1.4 on 2022-12-31 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Home", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Contact",
        ),
        migrations.DeleteModel(
            name="Posts",
        ),
    ]
